### ISSUE TITLE
Issues with the latest ULX3S board.

### ISSUE THREAD

**Issue by maded2** [lawrie/jupiter_ace#1]
hi,
   I ran into several issues trying to get this jupiter ace core to run on the latest ULX3S board.   I hope it is just me.

1)  in the Makefile.mk  it defined:  

`IDCODE ?= 0x21111043 # 12f`

which caused the nextpnr to generate 12F bit stream.  And I get the following error when trying to program the ULX3S with ujprog

`Found LFE5U-85F device, but the bitstream is for LFE5U-12F.`

I've remove the --idcode option from the nextpnr command and also added the DEVICE = 85k.  This appears to get a bit stream to work.

2)  The ULX3S appears to boot into a jupiter ace core.   I get an HDMI screen.   A black screen with blue vertical line on the left and what appears to be white square (cursor?).   But when I attach a PS/2 keyboard using a passive PS/2 to USB converter to the second usb port on the ULX3S. it doesn't allow me to enter any characters.  I see the keyboard leds lights up when the ULX3S boots up.  Any idea?

thanks.

**Comment by maded2** [comment]
I've resolved the issue.

**Comment by lawrie** [comment]
What was your solution?

I should probably update the Makefile to remove the IDCODEs as they are no longer needed.

The Jupiter Ace port is not a particularly good one. It doesn't support any way to load software, like a lot of the other retro ports do.

It could probably be made to support snapshots.

**Comment by maded2** [comment]
hi,
   I originally used a fork of your codebase which is linked from the ULX3S web site

https://github.com/emard/jupiter_ace

  Then I realised that fork didn't include your PS/2 keyboard fixes.  Hence I clone your repo directly and then it worked.  

thanks,
eddie
